## **The DataViz Challenge - Transforming EDA Projects to Dashboards**
## **Team Member: Sankhadip Nath**

## **Link to Tableau Dashboard: https://drive.google.com/file/d/1kqZox494xRU1cR1k0EWV5ppBuBjt7BAy/view?usp=drive_link

## **GitHub Link**

## **The DataViz Challenge** - **Transforming EDA Projects to Dashboards**

**Create Stunning Tableau Dashboard from the same dataset on which EDA was performed for the capstone project.**

.

**Problem Statement:**

In the context of Airbnb operations, how can the utilisation of Tableau facilitate a comprehensive comparative examination between Chicago and New Orleans, two diverse urban environments?

This inquiry seeks to leverage Tableau's visual analytics capabilities to uncover and illustrate the shared attributes, disparities, and distinctive patterns inherent to Airbnb's presence in these cities, thus elevating the depth and insightfulness of the study.

**Dataset Selection:**

For this EDA project, we have chosen the "Airbnb Listings Data" dataset from 2 major cities: Chicago and New Orleans. This dataset provides a comprehensive snapshot of various attributes related to Airbnb listings, such as property type, neighbourhood, pricing, availability, and more. The dataset is ideal for conducting an in-depth exploration of the local Airbnb market and deriving actionable insights.

**Why Airbnb:**

Airbnb, a prominent online platform, enables individuals to reserve accommodations spanning a spectrum from beds and rooms to apartments and entire homes across global locales. This user-centric platform serves as a conduit for seamless property rentals, negating the need for intricate intermediaries or substantial capital outlays. Notably, users can secure lodgings at significantly competitive rates relative to traditional hotels. Distinctively, Airbnb extends its reach to regions where convectional hotel presence might be limited, offering an avenue for lodging acquisition in underserved locales. Moreover, the inclination towards immersive local experiences often steers individuals towards selecting accommodations embedded within native communities, fostering a distinctive preference for authenticity and cultural engagement.

Airbnb Statistics • Over 4 million listings worldwide • 150 million users in 191 countries • Worldwide value is $32 billion • Global growth rate since 2009 - 153%

**Dataset Details:**

- Dataset Name: Airbnb Listings Data
- Source: [Link to dataset](http://insideairbnb.com/get-the-data/)
- Cities: Chicago & New Orleans
- Description: The Airbnb Listings Data contains information about different properties available for rent on Airbnb in a specific city. Each record represents a unique listing and includes attributes such as property type, neighbourhood, number of bedrooms, pricing, availability, host information, and more.

**Key Attributes**:

1. id: Unique identifier for each listing.

2. name: The title or name of the listing.

3. host_id: Unique identifier for the host of the property.

4. host_name: Name of the host.

5. neighbourhood_group: The broader area or group that the neighbourhood belongs to.

6. neighbourhood: Specific neighbourhood where the property is located.

7. latitude: Latitude coordinate of the property.

8. longitude: Longitude coordinate of the property.

9. room_type: Type of room (e.g., Private room, Entire home/apt, Shared room).

10. price: Price of the listing per night.

11. minimum_nights: Minimum number of nights required for booking.

12. number_of_reviews: Total number of reviews received for the listing.

13. last_review: Date of the last review.

14. reviews_per_month: Average number of reviews per month.

15. availability_365: Number of days the listing is available for booking in a year.

**Problem Areas to Explore:**

1. Which are the popular neighbourhoods, their average prices and no. of listings?

2. What is the percent share of different property types and room types?

3. How the pricing is varying with location, property type, and reviews?

4. What are the different correlations between type of hosts and factors like- reviews & price?

Divide the visualisation findings into 4 categories:

- Overview of Airbnb
- Property analysis
- Pricing analysis
- Host analysis

In [ ]:
#Importing necessary libraries
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#Importing the downloaded csv files into pandas dataframe for further analysis
chicago = pd.read_csv('/content/drive/MyDrive/Data Science/DATA SETS/Chicago listings.csv')
new_orelans = pd.read_csv('/content/drive/MyDrive/Data Science/DATA SETS/ New Orleans listings.csv')

In [ ]:
#Top 5 rows and columns view of Chicago dataset
chicago.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2384,https://www.airbnb.com/rooms/2384,20240323200240,2024-03-23,city scrape,Hyde Park - Walk to UChicago,You are invited stay in the guest room of my v...,The apartment is less than one block from beau...,https://a0.muscache.com/pictures/acf6b3c0-47f2...,2613,...,4.98,4.96,4.94,R17000015609,f,1,0,1,0,2.09
1,7126,https://www.airbnb.com/rooms/7126,20240323200240,2024-03-24,city scrape,Tiny Studio Apartment 94 Walk Score,A very small studio in a wonderful neighborhood.,"Ukrainian Village was just named ""Hottest Neig...",https://a0.muscache.com/pictures/51073/16c81c7...,17928,...,4.87,4.89,4.75,R24000114046,f,1,1,0,0,2.88
2,10945,https://www.airbnb.com/rooms/10945,20240323200240,2024-03-24,city scrape,The Biddle House (#1),Beautiful first floor apartment in Historic Ol...,NaN,https://a0.muscache.com/pictures/58d1a420-a24b...,33004,...,4.84,4.98,4.66,2209984,t,6,6,0,0,0.69
3,12140,https://www.airbnb.com/rooms/12140,20240323200240,2024-03-24,city scrape,Lincoln Park Guest House,Bed and Breakfast license issued by the City o...,The Guest House is in the heart of Chicago's m...,https://a0.muscache.com/pictures/miso/Hosting-...,46734,...,5.00,5.00,4.87,R20000055258,f,1,0,1,0,0.14
4,24833,https://www.airbnb.com/rooms/24833,20240323200240,2024-03-24,city scrape,Prime LincolnPark 1 Block Fullerton Express L ...,Perfect private entrance apartment one block f...,Lincoln Park is a great neighborhood where peo...,https://a0.muscache.com/pictures/ac17be6f-40bd...,101521,...,4.03,4.90,4.20,City registration pending,f,4,4,0,0,0.24

In [ ]:
#Bottom 5 rows and columns view of Chicago dataset
chicago.tail()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
7702,1116851419125146887,https://www.airbnb.com/rooms/1116851419125146887,20240323200240,2024-03-24,city scrape,Stylish 2BR Retreat in Hyde Park,Welcome to our inviting 2-bedroom apartment si...,"Hyde Park, located on Chicago's South Side, is...",https://a0.muscache.com/pictures/miso/Hosting-...,458971964,...,NaN,NaN,NaN,R21000074744,t,7,7,0,0,NaN
7703,1117394712148132475,https://www.airbnb.com/rooms/1117394712148132475,20240323200240,2024-03-24,city scrape,Vintage renovation in Logan Sq!,"Recent renovation! Tall ceilings, gorgeous woo...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,442832620,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
7704,1117438873812832956,https://www.airbnb.com/rooms/1117438873812832956,20240323200240,2024-03-24,city scrape,Guest king Room at Aloft Chicago Mag Mile,Welcome to Aloft Chicago Mag Mile <br /> <br /...,▶What's nearby <br />• In Downtown Chicago <br...,https://a0.muscache.com/pictures/prohost-api/H...,468436552,...,NaN,NaN,NaN,R65232147523,t,2,2,0,0,NaN
7705,1117439997700638787,https://www.airbnb.com/rooms/1117439997700638787,20240323200240,2024-03-24,city scrape,Guest 2 Queen Room at Aloft Chicago Mag Mile,Welcome to Aloft Chicago Mag Mile <br /> <br /...,▶What's nearby <br />• In Downtown Chicago <br...,https://a0.muscache.com/pictures/prohost-api/H...,468436552,...,NaN,NaN,NaN,R65232147523,t,2,2,0,0,NaN
7706,1117896281364781567,https://www.airbnb.com/rooms/1117896281364781567,20240323200240,2024-03-24,city scrape,Cali king suite,Your family will be close to everything when y...,NaN,https://a0.muscache.com/pictures/2fdb78f9-265d...,97416998,...,NaN,NaN,NaN,R21000075858,f,5,5,0,0,NaN

In [ ]:
#Getting information about all the null values across the chicago dataset
chicago.isnull().sum()

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1555
Length: 75, dtype: int64

In [ ]:
#Getting the description of all the numerical columns of Chicago dataset
chicago.describe()

,id,scrape_id,host_id,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,latitude,longitude,accommodates,bathrooms,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,7.707000e+03,7.707000e+03,7.707000e+03,7707.000000,7707.000000,0.0,7707.000000,7707.000000,7707.000000,7521.000000,...,6143.000000,6144.000000,6144.000000,6144.000000,6144.000000,7707.000000,7707.000000,7707.000000,7707.000000,6152.000000
mean,4.798164e+17,2.024032e+13,1.948637e+08,384.492020,432.263008,NaN,41.891764,-87.662794,4.390684,1.422949,...,4.768161,4.850627,4.867183,4.766558,4.697645,49.256650,46.540158,2.547035,0.109511,1.834826
std,4.434928e+17,3.906503e-03,1.770821e+08,1277.307206,1405.012522,NaN,0.063333,0.043779,3.036858,0.814847,...,0.376400,0.308851,0.314325,0.354800,0.388641,141.704968,142.265695,9.009192,1.174363,2.100680
min,2.384000e+03,2.024032e+13,2.153000e+03,1.000000,1.000000,NaN,41.646767,-87.846720,1.000000,0.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.010000
25%,4.073590e+07,2.024032e+13,3.851769e+07,1.000000,2.000000,NaN,41.858758,-87.685815,2.000000,1.000000,...,4.710000,4.830000,4.867500,4.710000,4.630000,1.000000,1.000000,0.000000,0.000000,0.540000
50%,6.279558e+17,2.024032e+13,1.217199e+08,5.000000,6.000000,NaN,41.896218,-87.658708,4.000000,1.000000,...,4.870000,4.940000,4.960000,4.880000,4.790000,4.000000,2.000000,0.000000,0.000000,1.480000
75%,9.067312e+17,2.024032e+13,3.701546e+08,21.000000,28.000000,NaN,41.935954,-87.631722,6.000000,2.000000,...,4.990000,5.000000,5.000000,4.980000,4.900000,17.000000,9.000000,1.000000,0.000000,2.640000
max,1.117896e+18,2.024032e+13,5.679786e+08,4914.000000,8920.000000,NaN,42.022200,-87.528420,16.000000,20.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,555.000000,555.000000,65.000000,20.000000,57.900000

In [ ]:
#Extracting the datatype of all the columns of the Chicago dataset
chicago.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7707 entries, 0 to 7706
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            7707 non-null   int64
 1   listing_url                                   7707 non-null   object
 2   scrape_id                                     7707 non-null   int64
 3   last_scraped                                  7707 non-null   object
 4   source                                        7707 non-null   object
 5   name                                          7707 non-null   object
 6   description                                   7622 non-null   object
 7   neighborhood_overview                         5428 non-null   object
 8   picture_url                                   7707 non-null   object
 9   host_id                                       7707 non-null   int64
 10  host_url                                      7707 non-null   object
 11  host_name                                     7707 non-null   object
 12  host_since                                    7707 non-null   object
 13  host_location                                 6288 non-null   object
 14  host_about                                    5238 non-null   object
 15  host_response_time                            7213 non-null   object
 16  host_response_rate                            7213 non-null   object
 17  host_acceptance_rate                          7377 non-null   object
 18  host_is_superhost                             7639 non-null   object
 19  host_thumbnail_url                            7707 non-null   object
 20  host_picture_url                              7707 non-null   object
 21  host_neighbourhood                            7504 non-null   object
 22  host_listings_count                           7707 non-null   int64
 23  host_total_listings_count                     7707 non-null   int64
 24  host_verifications                            7707 non-null   object
 25  host_has_profile_pic                          7707 non-null   object
 26  host_identity_verified                        7707 non-null   object
 27  neighbourhood                                 5429 non-null   object
 28  neighbourhood_cleansed                        7707 non-null   object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      7707 non-null   float64
 31  longitude                                     7707 non-null   float64
 32  property_type                                 7707 non-null   object
 33  room_type                                     7707 non-null   object
 34  accommodates                                  7707 non-null   int64
 35  bathrooms                                     7521 non-null   float64
 36  bathrooms_text                                7696 non-null   object
 37  bedrooms                                      7664 non-null   float64
 38  beds                                          7494 non-null   float64
 39  amenities                                     7707 non-null   object
 40  price                                         7522 non-null   object
 41  minimum_nights                                7707 non-null   int64
 42  maximum_nights                                7707 non-null   int64
 43  minimum_minimum_nights                        7707 non-null   int64
 44  maximum_minimum_nights                        7707 non-null   int64
 45  minimum_maximum_nights                        7707 non-null   int64
 46  maximum_maximum_nights                        7707 non-null   int64
 47  minimum_nights_avg_ntm                        7707 non-null   float64
 48  maximum_nights_avg_ntm                        7707 non-null   float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              7671 non-null   object
 51  availability_30                               7707 non-null   int64
 52  availability_60                               7707 non-null   int64
 53  availability_90                               7707 non-null   int64
 54  availability_365                              7707 non-null   int64
 55  calendar_last_scraped                         7707 non-null   object
 56  number_of_reviews                             7707 non-null   int64
 57  number_of_reviews_ltm                         7707 non-null   int64
 58  number_of_reviews_l30d                        7707 non-null   int64
 59  first_review                                  6152 non-null   object
 60  last_review                                   6152 non-null   object
 61  review_scores_rating                          6152 non-null   float64
 62  review_scores_accuracy                        6144 non-null   float64
 63  review_scores_cleanliness                     6143 non-null   float64
 64  review_scores_checkin                         6144 non-null   float64
 65  review_scores_communication                   6144 non-null   float64
 66  review_scores_location                        6144 non-null   float64
 67  review_scores_value                           6144 non-null   float64
 68  license                                       6247 non-null   object
 69  instant_bookable                              7707 non-null   object
 70  calculated_host_listings_count                7707 non-null   int64
 71  calculated_host_listings_count_entire_homes   7707 non-null   int64
 72  calculated_host_listings_count_private_rooms  7707 non-null   int64
 73  calculated_host_listings_count_shared_rooms   7707 non-null   int64
 74  reviews_per_month                             6152 non-null   float64
dtypes: float64(17), int64(23), object(35)
memory usage: 4.4+ MB

In [ ]:
#Changing the datatype of 'neighbourhood_group' column from float to string
chicago['neighbourhood_group_cleansed'].astype('str')

0       nan
1       nan
2       nan
3       nan
4       nan
       ...
7702    nan
7703    nan
7704    nan
7705    nan
7706    nan
Name: neighbourhood_group_cleansed, Length: 7707, dtype: object

In [ ]:
#Filling the null values with some string
chicago['neighbourhood_group_cleansed'].fillna('Chicago', inplace = True)

In [ ]:
#Filling the 'price' column with the mean price whereever the null values are present
chicago['bedrooms'].fillna(chicago['bedrooms'].mean(), inplace = True)

In [ ]:
#Top 5 rows and columns view of New_orelans dataset
new_orelans.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,19091,https://www.airbnb.com/rooms/19091,20240311215802,2024-03-11,city scrape,Fully Furnished Cozy Apartment,CITY OF NEW ORLEANS STR OWNER LICENSE NUMBER: ...,"NorthWest Carrollton, where this apartment is ...",https://a0.muscache.com/pictures/a5fdfd3b-5d81...,72880,...,4.98,4.68,4.91,"22-RSTR-14107, 22-OSTR-14105",f,1,1,0,0,2.97
1,71624,https://www.airbnb.com/rooms/71624,20240311215802,2024-03-11,city scrape,Ravenwood Manor (Historic Bywater),You are in for a very unique stay in a neighbo...,"Ours is a neighborhood made up of artists, mus...",https://a0.muscache.com/pictures/37488608/8cc1...,367223,...,4.98,4.83,4.89,"21-RSTR-18609, 22-OSTR-20720",f,1,1,0,0,1.88
2,74498,https://www.airbnb.com/rooms/74498,20240311215802,2024-03-11,city scrape,Maison Marais 1: Large Local Living,Maison Marais 1 is a stylish one-bedroom apart...,"This is a vibrant, diverse neighborhood of mos...",https://a0.muscache.com/pictures/73591836/a1f5...,391462,...,4.96,4.66,4.86,"Exempt: This listing is a licensed hotel, mote...",f,3,3,0,0,3.87
3,79536,https://www.airbnb.com/rooms/79536,20240311215802,2024-03-11,city scrape,FeelAtHomeInNewOrleans-PrivateApt,"Safe, clean & functional! Front porch and elev...","I love that it's down to earth, welcoming, his...",https://a0.muscache.com/pictures/f1037ebf-1573...,428362,...,4.98,4.53,4.87,"21-RSTR-18550, 21-OSTR-18392",t,1,1,0,0,4.53
4,79609,https://www.airbnb.com/rooms/79609,20240311215802,2024-03-11,city scrape,Moon Over Mazant - FIRST and FINEST in Bywater!,The Art of Hospitality,"First settled in 1806, Bywater is known for it...",https://a0.muscache.com/pictures/5c5da2eb-7434...,428909,...,4.99,4.84,4.94,"23-ISTR-02823, 23-OSTR-02823",f,1,0,1,0,3.12

In [ ]:
#Bottom 5 rows and columns view of New_orelans dataset
new_orelans.tail()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
7248,1108085930318924876,https://www.airbnb.com/rooms/1108085930318924876,20240311215802,2024-03-12,city scrape,Gorgeous Uptown NOLA Suite,Enjoy a stylish experience at this centrally-l...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,483061834,...,NaN,NaN,NaN,"23NSTR-15850, 26OSTR-15850",f,1,0,1,0,NaN
7249,1108090238689884268,https://www.airbnb.com/rooms/1108090238689884268,20240311215802,2024-03-12,city scrape,Renovated Retreat with Heated Pool | Steps to FQ,"This single-family home, with heated pool, loc...",Our home is a 6 minute walk from the edge of t...,https://a0.muscache.com/pictures/prohost-api/H...,151238588,...,NaN,NaN,NaN,"20-CSTR-26928, 20-OSTR-26928",t,8,8,0,0,NaN
7250,1108873819642943328,https://www.airbnb.com/rooms/1108873819642943328,20240311215802,2024-03-11,city scrape,The Bartholomew - Bywater's Best,Enjoy a stylish and peaceful experience at thi...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,12623279,...,NaN,NaN,NaN,"23NSTR-12345, 20ostr-12345",t,1,1,0,0,NaN
7251,1108995530911454316,https://www.airbnb.com/rooms/1108995530911454316,20240311215802,2024-03-12,city scrape,Jazzy vibrant getaway,This vibrant retreat is perfect for groups of ...,This is a convenient location for those lookin...,https://a0.muscache.com/pictures/miso/Hosting-...,508600133,...,NaN,NaN,NaN,"23-NSTR-29572, 21OSTR-29572",t,12,12,0,0,NaN
7252,1109317593885640515,https://www.airbnb.com/rooms/1109317593885640515,20240311215802,2024-03-12,city scrape,Beautiful Condo near French Quarter!,Located blocks from the French Quarter. This s...,"Treme, the birthplace of Jazz, is one of the o...",https://a0.muscache.com/pictures/prohost-api/H...,384072218,...,NaN,NaN,NaN,"22-CSTR-18898, 21-OSTR-12387",t,3,3,0,0,NaN

In [ ]:
##Getting information about all the null values across the new_orelans dataset
new_orelans.isna().sum()

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1140
Length: 75, dtype: int64

In [ ]:
#Getting the description of all the numerical columns of new_orelans dataset
new_orelans.describe()

,id,scrape_id,host_id,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,latitude,longitude,accommodates,bathrooms,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,7.253000e+03,7.253000e+03,7.253000e+03,7253.000000,7253.000000,0.0,7253.000000,7253.000000,7253.000000,6225.000000,...,6107.000000,6106.000000,6107.000000,6106.000000,6106.000000,7253.000000,7253.000000,7253.000000,7253.000000,6113.000000
mean,3.766119e+17,2.024031e+13,1.964047e+08,101.332966,169.656418,NaN,29.958630,-90.073729,4.971322,1.697912,...,4.794295,4.882930,4.868818,4.727946,4.724130,12.540052,11.048945,1.397353,0.080105,1.756894
std,4.329136e+17,0.000000e+00,1.808959e+08,427.463401,766.026590,NaN,0.024516,0.031619,3.055653,1.091468,...,0.330186,0.294667,0.303670,0.358012,0.361294,20.591594,19.591272,5.717938,1.218336,1.791569
min,1.909100e+04,2.024031e+13,9.710000e+02,1.000000,1.000000,NaN,29.897680,-90.136460,1.000000,0.000000,...,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.010000
25%,2.776527e+07,2.024031e+13,3.907766e+07,1.000000,2.000000,NaN,29.942440,-90.089580,2.000000,1.000000,...,4.740000,4.880000,4.860000,4.620000,4.670000,1.000000,1.000000,0.000000,0.000000,0.580000
50%,5.123379e+07,2.024031e+13,1.223807e+08,3.000000,5.000000,NaN,29.957540,-90.073547,4.000000,1.000000,...,4.890000,4.960000,4.950000,4.830000,4.810000,3.000000,2.000000,0.000000,0.000000,1.410000
75%,8.123258e+17,2.024031e+13,3.495748e+08,17.000000,24.000000,NaN,29.969840,-90.062730,6.000000,2.000000,...,4.980000,5.000000,5.000000,4.960000,4.910000,12.000000,9.000000,0.000000,0.000000,2.470000
max,1.109318e+18,2.024031e+13,5.653717e+08,2967.000000,8913.000000,NaN,30.161040,-89.737090,16.000000,18.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,90.000000,90.000000,48.000000,21.000000,47.680000

In [ ]:
#Extracting the datatype of all the columns of the new_orelans dataset
new_orelans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            7253 non-null   int64
 1   listing_url                                   7253 non-null   object
 2   scrape_id                                     7253 non-null   int64
 3   last_scraped                                  7253 non-null   object
 4   source                                        7253 non-null   object
 5   name                                          7253 non-null   object
 6   description                                   7165 non-null   object
 7   neighborhood_overview                         5005 non-null   object
 8   picture_url                                   7252 non-null   object
 9   host_id                                       7253 non-null   int64
 10  host_url                                      7253 non-null   object
 11  host_name                                     7253 non-null   object
 12  host_since                                    7253 non-null   object
 13  host_location                                 5228 non-null   object
 14  host_about                                    4125 non-null   object
 15  host_response_time                            5930 non-null   object
 16  host_response_rate                            5930 non-null   object
 17  host_acceptance_rate                          6140 non-null   object
 18  host_is_superhost                             7232 non-null   object
 19  host_thumbnail_url                            7253 non-null   object
 20  host_picture_url                              7253 non-null   object
 21  host_neighbourhood                            6819 non-null   object
 22  host_listings_count                           7253 non-null   int64
 23  host_total_listings_count                     7253 non-null   int64
 24  host_verifications                            7253 non-null   object
 25  host_has_profile_pic                          7253 non-null   object
 26  host_identity_verified                        7253 non-null   object
 27  neighbourhood                                 5005 non-null   object
 28  neighbourhood_cleansed                        7253 non-null   object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      7253 non-null   float64
 31  longitude                                     7253 non-null   float64
 32  property_type                                 7253 non-null   object
 33  room_type                                     7253 non-null   object
 34  accommodates                                  7253 non-null   int64
 35  bathrooms                                     6225 non-null   float64
 36  bathrooms_text                                7248 non-null   object
 37  bedrooms                                      7099 non-null   float64
 38  beds                                          6198 non-null   float64
 39  amenities                                     7253 non-null   object
 40  price                                         6217 non-null   object
 41  minimum_nights                                7253 non-null   int64
 42  maximum_nights                                7253 non-null   int64
 43  minimum_minimum_nights                        7253 non-null   int64
 44  maximum_minimum_nights                        7253 non-null   int64
 45  minimum_maximum_nights                        7253 non-null   int64
 46  maximum_maximum_nights                        7253 non-null   int64
 47  minimum_nights_avg_ntm                        7253 non-null   float64
 48  maximum_nights_avg_ntm                        7253 non-null   float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              7033 non-null   object
 51  availability_30                               7253 non-null   int64
 52  availability_60                               7253 non-null   int64
 53  availability_90                               7253 non-null   int64
 54  availability_365                              7253 non-null   int64
 55  calendar_last_scraped                         7253 non-null   object
 56  number_of_reviews                             7253 non-null   int64
 57  number_of_reviews_ltm                         7253 non-null   int64
 58  number_of_reviews_l30d                        7253 non-null   int64
 59  first_review                                  6113 non-null   object
 60  last_review                                   6113 non-null   object
 61  review_scores_rating                          6113 non-null   float64
 62  review_scores_accuracy                        6105 non-null   float64
 63  review_scores_cleanliness                     6107 non-null   float64
 64  review_scores_checkin                         6106 non-null   float64
 65  review_scores_communication                   6107 non-null   float64
 66  review_scores_location                        6106 non-null   float64
 67  review_scores_value                           6106 non-null   float64
 68  license                                       5978 non-null   object
 69  instant_bookable                              7253 non-null   object
 70  calculated_host_listings_count                7253 non-null   int64
 71  calculated_host_listings_count_entire_homes   7253 non-null   int64
 72  calculated_host_listings_count_private_rooms  7253 non-null   int64
 73  calculated_host_listings_count_shared_rooms   7253 non-null   int64
 74  reviews_per_month                             6113 non-null   float64
dtypes: float64(17), int64(23), object(35)
memory usage: 4.2+ MB

In [ ]:
#Changing the datatype of 'neighbourhood_group' column from float to string
new_orelans['neighbourhood_group_cleansed'].astype('str')

0       nan
1       nan
2       nan
3       nan
4       nan
       ...
7248    nan
7249    nan
7250    nan
7251    nan
7252    nan
Name: neighbourhood_group_cleansed, Length: 7253, dtype: object

In [ ]:
#Filling the null values with some string
new_orelans['neighbourhood_group_cleansed'].fillna('New Orelans', inplace = True)